name: drafted-web
region: ams
static_sites:
  - name: website
    github:
      repo: Fulviuus/drafted-web
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: hugo
    build_command: hugo --gc --minify
    output_dir: public
    index_document: index.html
